const PREFIX = 'MAIN_PAGE';

export const MAIN_PAGE_ACTION = {
    GET_BOARDS: `${PREFIX}_GET_BOARD`,
    CREATE_BOARD: `${PREFIX}_CREATE_BOARD`,
    CLEAR_BOARDS_DATA: `${PREFIX}_CLEAR_BOARDS_DATA`
};
