const PREFIX = 'BOARD';

export const BOARD = {
    GET_BOARD: `${PREFIX}_GET_BOARD`,
    CREATE_CARD: `${PREFIX}_CREATE_CARD`,
    CREATE_LIST: `${PREFIX}_CREATE_LIST`,
    UPDATE_LIST: `${PREFIX}_UPDATE_LIST`,
    UPDATE_CARD: `${PREFIX}_UPDATE_CARD`,
    DELETE_CARD: `${PREFIX}_DELETE_CARD`,
    DELETE_LIST: `${PREFIX}_DELETE_LIST`
};
